### ISSUE TITLE
Server not listening if configured with real ip

### ISSUE THREAD

**Issue by Rakin061** [quangtqag/RealtimePythonChat#1]
Hello, 

I wanna deploy this app for production. So, I have to configure the `socketio.run` to run in a real ip (public ip)

So, I changed the code of `server.py` in main like that:-

`socketio.run(app,host='0.0.0.0',port=5000)`

But, it's not working for public ip. In local ip and localhost it's working fine. 

Could you give any fix or help to resolve this issue. 

Thanks in advance.

**Comment by quangtqag** [comment]
Hello,
I no longer maintain this source. You can add parameter `debug=True` in function `socketio.run`, perhaps it will print out some problems to you.
`socketio.run(app,host='0.0.0.0',port=5000, debug=True)`
I hope it will help you.

**Comment by Rakin061** [comment]
Thanks for the help. 
I think this issue could be regarded as closed.
